/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Side_Tab_Using_CardLayout;

import java.awt.CardLayout;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author user
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setup_for_JFrame();
        settext_center();
        add_Events();
    }
    private void setup_for_JFrame()
    {
        this.setSize(664, 426);
        this.setLocationRelativeTo(null);
        
    }
    private void add_Events()
    {
        add_Events_for_Label();
    }
    private void settext_center()
    {
        this.jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
         this.jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
          this.jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
           this.jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
    }
    private void add_Events_for_Label()
    {
        Controll obj1 = new Controll(jLabel1, this);
         Controll obj2 = new Controll(jLabel2, this);
          Controll obj3 = new Controll(jLabel3, this);
           Controll obj4 = new Controll(jLabel4, this);
          
        jLabel1.addMouseListener(obj1);
        jLabel2.addMouseListener(obj2);
        jLabel3.addMouseListener(obj3);
        jLabel4.addMouseListener(obj4);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SideTab = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ca2 = new javax.swing.JPanel();
        ca3 = new javax.swing.JPanel();
        ca4 = new javax.swing.JPanel();
        ca5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        SideTab.setBackground(new java.awt.Color(0, 0, 0));
        SideTab.setPreferredSize(new java.awt.Dimension(150, 426));
        SideTab.setRequestFocusEnabled(false);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setEnabled(false);
        jPanel4.setFocusTraversalPolicyProvider(true);
        jPanel4.setPreferredSize(new java.awt.Dimension(10, 50));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        SideTab.add(jPanel4);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 250));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inbox");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel2.add(jLabel1);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sent");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel2.add(jLabel2);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Archive");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel2.add(jLabel3);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Trash");
        jLabel4.setToolTipText("");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel2.add(jLabel4);

        SideTab.add(jPanel2);

        jPanel1.add(SideTab, java.awt.BorderLayout.WEST);

        jPanel3.setLayout(new java.awt.CardLayout());

        ca2.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout ca2Layout = new javax.swing.GroupLayout(ca2);
        ca2.setLayout(ca2Layout);
        ca2Layout.setHorizontalGroup(
            ca2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        ca2Layout.setVerticalGroup(
            ca2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        jPanel3.add(ca2, "card2");
        ca2.getAccessibleContext().setAccessibleDescription("");

        ca3.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout ca3Layout = new javax.swing.GroupLayout(ca3);
        ca3.setLayout(ca3Layout);
        ca3Layout.setHorizontalGroup(
            ca3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        ca3Layout.setVerticalGroup(
            ca3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        jPanel3.add(ca3, "card3");

        ca4.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout ca4Layout = new javax.swing.GroupLayout(ca4);
        ca4.setLayout(ca4Layout);
        ca4Layout.setHorizontalGroup(
            ca4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        ca4Layout.setVerticalGroup(
            ca4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        jPanel3.add(ca4, "card4");

        ca5.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout ca5Layout = new javax.swing.GroupLayout(ca5);
        ca5.setLayout(ca5Layout);
        ca5Layout.setHorizontalGroup(
            ca5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        ca5Layout.setVerticalGroup(
            ca5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        jPanel3.add(ca5, "card5");

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SideTab;
    private javax.swing.JPanel ca2;
    private javax.swing.JPanel ca3;
    private javax.swing.JPanel ca4;
    private javax.swing.JPanel ca5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    public void show_cardLayout(String s) // s là tên của cardLayout để tham chiếu đến có thể xem trong card Name của properties.
    {
        CardLayout card = new CardLayout();
        card = (CardLayout)jPanel3.getLayout();
        card.show(jPanel3, s);// jPanel3 là jpanel chứa Layout này.
    }
    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    
    
}
